In [11]:
import pandas as pd

In [13]:
hhz = pd.read_excel('HHZ.xlsx')
pc = pd.read_excel('PC2021.xlsx')

print(type(hhz))
print(hhz)
print(pc)

<class 'pandas.core.frame.DataFrame'>
              Unnamed: 0  Unnamed: 1 Unnamed: 2 Unnamed: 3    汉名 Unnamed: 5  \
0            Stanley Abe         Abe    Stanley       阿部贤次  阿部贤次       阿部賢次
1           Pedro Acosta      Acosta      Pedro        柯彼得   柯彼得        柯彼得
2           Harold Acton       Acton     Harold        艾克顿   艾克顿        艾克頓
3          Kiroku Adachi      Adachi     Kiroku       足立喜六  足立喜六       足立喜六
4           Wendi Adamek      Adamek      Wendi        韦闻笛   韦闻笛        韋聞笛
...                  ...         ...        ...        ...   ...        ...
1951              Ke Zou         Zou         Ke         邹科    邹科         鄒科
1952         Xiuying Zou         Zou    Xiuying        邹秀英   邹秀英        鄒秀英
1953          Jiping Zuo         Zuo     Jiping        左际平   左际平        左際平
1954        Erik Zürcher     Zürcher       Erik        许理和   许理和        許理和
1955  Harriet Zurndorfer  Zurndorfer    Harriet        宋汉理   宋汉理        宋漢理

     Unnamed: 6 Unnamed: 7  Unnamed: 8 Unnamed: 9 Unnamed: 10  Unnamed: 11
0           NaN        NaN         Abe    Stanley         NaN          NaN
1           NaN        NaN      Acosta      Pedro         NaN          NaN
2           NaN        NaN       Acton     Harold         NaN          NaN
3           NaN        NaN      Adachi     Kiroku         NaN          NaN
4           NaN        NaN      Adamek      Wendi         NaN          NaN
...         ...        ...         ...        ...         ...          ...
1951        NaN        NaN         Zou         Ke         NaN          NaN
1952        NaN        NaN         Zou    Xiuying         NaN          NaN
1953        NaN        NaN         Zuo     Jiping         NaN          NaN
1954        NaN        NaN     Zurcher       Erik         NaN          NaN
1955        NaN        NaN  Zurndorfer    Harriet         NaN          NaN

[1956 rows x 12 columns]
              Unnamed: 0  Unnamed: 1 Unnamed: 2 Unnamed: 3   汉名 Unnamed: 5  \
0             Pascal Abb         Abb     Pascal        艾沛思  艾沛思        艾沛思
1               Oded Abt         Abt       Oded        歐克德  欧克德        歐克德
2           Harold Acton       Acton     Harold        艾克頓  艾克顿        艾克頓
3           Piotr Adamek      Adamek      Piotr        顧孝永  顾孝永        顧孝永
4           Wendi Adamek      Adamek      Wendi        韋聞笛  韦闻笛        韋聞笛
...                  ...         ...        ...        ...  ...        ...
3699         Xuejing Zuo         Zuo    Xuejing        左雪靜  左雪静        左雪靜
3700        Erik Zürcher     Zürcher       Erik        許理和  许理和        許理和
3701         David Zweig       Zweig      David        崔大偉  崔大伟        崔大偉
3702        Tobias Zuern       Zuern     Tobias        陶全恩  陶全恩        陶全恩
3703  Harriet Zurndorfer  Zurndorfer    Harriet        宋漢理  宋汉理        宋漢理

     Unnamed: 6 Unnamed: 7  Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11
0           NaN        NaN         Abb     Pascal         NaN         NaN
1           NaN        NaN         Abt       Oded         NaN         NaN
2           NaN        NaN       Acton     Harold         NaN         NaN
3           NaN        NaN      Adamek      Piotr         NaN         NaN
4           NaN        NaN      Adamek      Wendi         NaN         NaN
...         ...        ...         ...        ...         ...         ...
3699        NaN        NaN         Zuo    Xuejing         NaN         NaN
3700        NaN        NaN     Zurcher       Erik         NaN         NaN
3701        NaN        NaN       Zweig      David         NaN         NaN
3702        NaN        NaN       Zuern     Tobias         NaN         NaN
3703        NaN        NaN  Zurndorfer    Harriet         NaN         NaN

[3704 rows x 12 columns]

In [14]:
合集 = hhz.append(pc,ignore_index=True)
合集.shape

(5660, 12)

In [19]:
合集重复行 = 合集.duplicated(['汉名'],keep=False)
合集重复数据 = 合集.loc[合集重复行,:]

In [20]:
HHZ加上重复数据 = hhz.append(合集重复数据,ignore_index=True)
PC加上重复数据 = pc.append(合集重复数据,ignore_index=True)

In [21]:
HHZ无共有行 = HHZ加上重复数据.duplicated(['汉名'],keep=False)
PC无共有行 = PC加上重复数据.duplicated(['汉名'],keep=False)

In [7]:
# 合集無重複 = 合集.drop_duplicates(['汉名'],keep=False)
# 合集無重複.shape

(2706, 12)

In [24]:
HHZ獨有部分 = HHZ加上重复数据.drop_duplicates(['汉名'],keep=False)
PC独有部分 = PC加上重复数据.drop_duplicates(['汉名'],keep=False)

In [25]:
HHZ獨有部分

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,汉名,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Stanley Abe,Abe,Stanley,阿部贤次,阿部贤次,阿部賢次,NaN,NaN,Abe,Stanley,NaN,NaN
1,Pedro Acosta,Acosta,Pedro,柯彼得,柯彼得,柯彼得,NaN,NaN,Acosta,Pedro,NaN,NaN
3,Kiroku Adachi,Adachi,Kiroku,足立喜六,足立喜六,足立喜六,NaN,NaN,Adachi,Kiroku,NaN,NaN
6,Guilhem André,André,Guilhem,安炜,安炜,安煒,NaN,NaN,Andre,Guilhem,NaN,NaN
13,Joseph Marie Amiot,Amiot,Joseph Marie,钱德明,钱德明,錢德明,NaN,NaN,Amiot,Joseph Marie,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1935,Min Zhou,Zhou,Min,周敏,周敏,周敏,NaN,NaN,Zhou,Min,NaN,NaN
1940,Xun Zhou,Zhou,Xun,周逊,周逊,周遜,NaN,NaN,Zhou,Xun,NaN,NaN
1942,Yu Zhou,Zhou,Yu,周宇,周宇,周宇,NaN,NaN,Zhou,Yu,NaN,NaN
1945,Zhiqun Zhu,Zhu,Zhiqun,朱志群,朱志群,朱志羣,NaN,NaN,Zhu,Zhiqun,NaN,NaN
1949,Angelo Zottoli,Zottoli,Angelo,晁德莅,晁德莅,晁德蒞,NaN,NaN,Zottoli,Angelo,NaN,NaN

In [26]:
PC独有部分

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,汉名,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Pascal Abb,Abb,Pascal,艾沛思,艾沛思,艾沛思,NaN,NaN,Abb,Pascal,NaN,NaN
3,Piotr Adamek,Adamek,Piotr,顧孝永,顾孝永,顧孝永,NaN,NaN,Adamek,Piotr,NaN,NaN
6,Nick Admussen,Admussen,Nick,安敏軒,安敏轩,安敏軒,NaN,NaN,Admussen,Nick,NaN,NaN
7,Liubov Afonina,Afonina,Liubov,劉雨馨,刘雨馨,劉雨馨,NaN,NaN,Afonina,Liubov,NaN,NaN
8,Byung-joon Ahn,Ahn,Byung-joon,安秉俊,安秉俊,安秉俊,NaN,NaN,Ahn,Byung-joon,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3693,Nicolas David Zorzin,Zorzin,Nicolas David,佐金,佐金,佐金,NaN,NaN,Zorzin,Nicolas David,NaN,NaN
3697,Ghil’ad Zuckermann,Zuckermann,Ghil’ad,諸葛漫,诸葛漫,諸葛漫,NaN,NaN,Zuckermann,Ghil’ad,NaN,NaN
3699,Xuejing Zuo,Zuo,Xuejing,左雪靜,左雪静,左雪靜,NaN,NaN,Zuo,Xuejing,NaN,NaN
3701,David Zweig,Zweig,David,崔大偉,崔大伟,崔大偉,NaN,NaN,Zweig,David,NaN,NaN
3702,Tobias Zuern,Zuern,Tobias,陶全恩,陶全恩,陶全恩,NaN,NaN,Zuern,Tobias,NaN,NaN

In [27]:
HHZ獨有部分.to_excel('HHZ表格独有部分.xlsx')

In [28]:
PC独有部分.to_excel('柯氏独有部分.xlsx')